/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jobject stub_ADGLSurfaceView_ADGLSurfaceView_0(jmethodID id, va_list args);
extern jboolean stub_ADGLSurfaceView_onKeyDown_1(jmethodID id, va_list args);
extern jboolean stub_ADGLSurfaceView_onTouchEvent_2(jmethodID id, va_list args);
extern void stub_ADRenderer_onSurfaceCreated_3(jmethodID id, va_list args);
extern void stub_ADRenderer_onSurfaceChanged_4(jmethodID id, va_list args);
extern void stub_ADRenderer_onDrawFrame_5(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVALoadSample_6(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVAPlaySample_7(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAStopSample_8(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVASaveFile_9(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVADeleteFile_10(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVALoadFile_11(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVAFileSize_12(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVAFindFile_13(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVASetMusicVolume_14(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAPlayMusic_15(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAStopMusic_16(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAPauseMusic_17(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAUnPauseMusic_18(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAMusicRestart_19(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAUnJpg_20(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAUnPng_21(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAUnZip_22(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAOpenFeintOpen_23(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAOpenFeintLastLoggedInUserID_24(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAOpenFeintSubmit_25(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAOpenFeintUnlock_26(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVAOpenFeintIsUserLoggedIn_27(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVAOpenFeintIsOnline_28(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVATime_29(jmethodID id, va_list args);
extern jint stub_ADRenderer_JAVATimeHi_30(jmethodID id, va_list args);
extern void stub_ADRenderer_JAVAVibrate_31(jmethodID id, va_list args);
extern jobject stub_AccelerometerListener_AccelerometerListener_32(jmethodID id, va_list args);
extern void stub_AccelerometerListener_start_33(jmethodID id, va_list args);
extern void stub_AccelerometerListener_stop_34(jmethodID id, va_list args);
extern void stub_AccelerometerListener_onAccuracyChanged_35(jmethodID id, va_list args);
extern void stub_AccelerometerListener_onSensorChanged_36(jmethodID id, va_list args);
extern void stub_MyOpenFeintDelegate_userLoggedIn_37(jmethodID id, va_list args);
extern jobject stub_SnailMailActivity_SnailMailActivity_38(jmethodID id, va_list args);
extern jobject stub_SnailMailActivity_getContext_39(jmethodID id, va_list args);
extern void stub_SnailMailActivity_wprintf_40(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onCreate_41(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onDestroy_42(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onRestart_43(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onStart_44(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onStop_45(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onPause_46(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onResume_47(jmethodID id, va_list args);
extern void stub_SnailMailActivity_onWindowFocusChanged_48(jmethodID id, va_list args);
extern jobject stub_SnailMailApplication_SnailMailApplication_49(jmethodID id, va_list args);
extern jobject stub_SnailMailApplication_getContext_50(jmethodID id, va_list args);
extern void stub_SnailMailApplication_onCreate_51(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "ADGLSurfaceView", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.ADGLSurfaceView
    { 1, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.sandlotgames.snailmail.ADGLSurfaceView
    { 2, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.sandlotgames.snailmail.ADGLSurfaceView
    { 3, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 4, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 5, "onDrawFrame", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 6, "JAVALoadSample", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 7, "JAVAPlaySample", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 8, "JAVAStopSample", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 9, "JAVASaveFile", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 10, "JAVADeleteFile", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 11, "JAVALoadFile", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 12, "JAVAFileSize", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 13, "JAVAFindFile", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 14, "JAVASetMusicVolume", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 15, "JAVAPlayMusic", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 16, "JAVAStopMusic", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 17, "JAVAPauseMusic", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 18, "JAVAUnPauseMusic", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 19, "JAVAMusicRestart", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 20, "JAVAUnJpg", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 21, "JAVAUnPng", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 22, "JAVAUnZip", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 23, "JAVAOpenFeintOpen", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 24, "JAVAOpenFeintLastLoggedInUserID", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 25, "JAVAOpenFeintSubmit", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 26, "JAVAOpenFeintUnlock", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 27, "JAVAOpenFeintIsUserLoggedIn", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 28, "JAVAOpenFeintIsOnline", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 29, "JAVATime", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 30, "JAVATimeHi", METHOD_TYPE_INT },  // com.sandlotgames.snailmail.ADRenderer
    { 31, "JAVAVibrate", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.ADRenderer
    { 32, "AccelerometerListener", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.AccelerometerListener
    { 33, "start", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.AccelerometerListener
    { 34, "stop", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.AccelerometerListener
    { 35, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.AccelerometerListener
    { 36, "onSensorChanged", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.AccelerometerListener
    { 37, "userLoggedIn", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.MyOpenFeintDelegate
    { 38, "SnailMailActivity", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.SnailMailActivity
    { 39, "getContext", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.SnailMailActivity
    { 40, "wprintf", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 41, "onCreate", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 42, "onDestroy", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 43, "onRestart", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 44, "onStart", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 45, "onStop", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 46, "onPause", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 47, "onResume", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 48, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailActivity
    { 49, "SnailMailApplication", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.SnailMailApplication
    { 50, "getContext", METHOD_TYPE_OBJECT },  // com.sandlotgames.snailmail.SnailMailApplication
    { 51, "onCreate", METHOD_TYPE_VOID },  // com.sandlotgames.snailmail.SnailMailApplication
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 0, stub_ADGLSurfaceView_ADGLSurfaceView_0 },
    { 32, stub_AccelerometerListener_AccelerometerListener_32 },
    { 38, stub_SnailMailActivity_SnailMailActivity_38 },
    { 39, stub_SnailMailActivity_getContext_39 },
    { 49, stub_SnailMailApplication_SnailMailApplication_49 },
    { 50, stub_SnailMailApplication_getContext_50 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 1, stub_ADGLSurfaceView_onKeyDown_1 },
    { 2, stub_ADGLSurfaceView_onTouchEvent_2 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 3, stub_ADRenderer_onSurfaceCreated_3 },
    { 4, stub_ADRenderer_onSurfaceChanged_4 },
    { 5, stub_ADRenderer_onDrawFrame_5 },
    { 8, stub_ADRenderer_JAVAStopSample_8 },
    { 10, stub_ADRenderer_JAVADeleteFile_10 },
    { 11, stub_ADRenderer_JAVALoadFile_11 },
    { 14, stub_ADRenderer_JAVASetMusicVolume_14 },
    { 15, stub_ADRenderer_JAVAPlayMusic_15 },
    { 16, stub_ADRenderer_JAVAStopMusic_16 },
    { 17, stub_ADRenderer_JAVAPauseMusic_17 },
    { 18, stub_ADRenderer_JAVAUnPauseMusic_18 },
    { 19, stub_ADRenderer_JAVAMusicRestart_19 },
    { 20, stub_ADRenderer_JAVAUnJpg_20 },
    { 21, stub_ADRenderer_JAVAUnPng_21 },
    { 22, stub_ADRenderer_JAVAUnZip_22 },
    { 23, stub_ADRenderer_JAVAOpenFeintOpen_23 },
    { 24, stub_ADRenderer_JAVAOpenFeintLastLoggedInUserID_24 },
    { 25, stub_ADRenderer_JAVAOpenFeintSubmit_25 },
    { 26, stub_ADRenderer_JAVAOpenFeintUnlock_26 },
    { 31, stub_ADRenderer_JAVAVibrate_31 },
    { 33, stub_AccelerometerListener_start_33 },
    { 34, stub_AccelerometerListener_stop_34 },
    { 35, stub_AccelerometerListener_onAccuracyChanged_35 },
    { 36, stub_AccelerometerListener_onSensorChanged_36 },
    { 37, stub_MyOpenFeintDelegate_userLoggedIn_37 },
    { 40, stub_SnailMailActivity_wprintf_40 },
    { 41, stub_SnailMailActivity_onCreate_41 },
    { 42, stub_SnailMailActivity_onDestroy_42 },
    { 43, stub_SnailMailActivity_onRestart_43 },
    { 44, stub_SnailMailActivity_onStart_44 },
    { 45, stub_SnailMailActivity_onStop_45 },
    { 46, stub_SnailMailActivity_onPause_46 },
    { 47, stub_SnailMailActivity_onResume_47 },
    { 48, stub_SnailMailActivity_onWindowFocusChanged_48 },
    { 51, stub_SnailMailApplication_onCreate_51 },
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 6, stub_ADRenderer_JAVALoadSample_6 },
    { 7, stub_ADRenderer_JAVAPlaySample_7 },
    { 9, stub_ADRenderer_JAVASaveFile_9 },
    { 12, stub_ADRenderer_JAVAFileSize_12 },
    { 13, stub_ADRenderer_JAVAFindFile_13 },
    { 27, stub_ADRenderer_JAVAOpenFeintIsUserLoggedIn_27 },
    { 28, stub_ADRenderer_JAVAOpenFeintIsOnline_28 },
    { 29, stub_ADRenderer_JAVATime_29 },
    { 30, stub_ADRenderer_JAVATimeHi_30 },
};

