/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.sandlotgames.snailmail.ADGLSurfaceView ----
jobject stub_ADGLSurfaceView_ADGLSurfaceView_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADGLSurfaceView.ADGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jboolean stub_ADGLSurfaceView_onKeyDown_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADGLSurfaceView.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_ADGLSurfaceView_onTouchEvent_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADGLSurfaceView.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

// ---- com.sandlotgames.snailmail.ADRenderer ----
void stub_ADRenderer_onSurfaceCreated_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_ADRenderer_onSurfaceChanged_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_ADRenderer_onDrawFrame_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

jint stub_ADRenderer_JAVALoadSample_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVALoadSample(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jint stub_ADRenderer_JAVAPlaySample_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAPlaySample(IF)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
    return 0;
}

void stub_ADRenderer_JAVAStopSample_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAStopSample(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jint stub_ADRenderer_JAVASaveFile_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVASaveFile(Ljava/lang/String;[BI)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
    jint arg2 = (jint) va_arg(args, int);
    return 0;
}

void stub_ADRenderer_JAVADeleteFile_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVADeleteFile(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_ADRenderer_JAVALoadFile_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVALoadFile(Ljava/lang/String;[BI)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
    jint arg2 = (jint) va_arg(args, int);
}

jint stub_ADRenderer_JAVAFileSize_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAFileSize(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jint stub_ADRenderer_JAVAFindFile_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAFindFile(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

void stub_ADRenderer_JAVASetMusicVolume_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVASetMusicVolume(F)V called -- fill in from the real Java impl (jadx).");
    jfloat arg0 = (jfloat) va_arg(args, double);
}

void stub_ADRenderer_JAVAPlayMusic_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAPlayMusic(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_ADRenderer_JAVAStopMusic_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAStopMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_ADRenderer_JAVAPauseMusic_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAPauseMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_ADRenderer_JAVAUnPauseMusic_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAUnPauseMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_ADRenderer_JAVAMusicRestart_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAMusicRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_ADRenderer_JAVAUnJpg_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAUnJpg([B[B)V called -- fill in from the real Java impl (jadx).");
    jbyteArray arg0 = (jbyteArray) va_arg(args, jobject);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
}

void stub_ADRenderer_JAVAUnPng_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAUnPng([B[B)V called -- fill in from the real Java impl (jadx).");
    jbyteArray arg0 = (jbyteArray) va_arg(args, jobject);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
}

void stub_ADRenderer_JAVAUnZip_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAUnZip([B[B)V called -- fill in from the real Java impl (jadx).");
    jbyteArray arg0 = (jbyteArray) va_arg(args, jobject);
    jbyteArray arg1 = (jbyteArray) va_arg(args, jobject);
}

void stub_ADRenderer_JAVAOpenFeintOpen_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintOpen()V called -- fill in from the real Java impl (jadx).");
}

void stub_ADRenderer_JAVAOpenFeintLastLoggedInUserID_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintLastLoggedInUserID([B)V called -- fill in from the real Java impl (jadx).");
    jbyteArray arg0 = (jbyteArray) va_arg(args, jobject);
}

void stub_ADRenderer_JAVAOpenFeintSubmit_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintSubmit(Ljava/lang/String;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_ADRenderer_JAVAOpenFeintUnlock_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintUnlock(Ljava/lang/String;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
}

jint stub_ADRenderer_JAVAOpenFeintIsUserLoggedIn_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintIsUserLoggedIn()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_ADRenderer_JAVAOpenFeintIsOnline_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAOpenFeintIsOnline()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_ADRenderer_JAVATime_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVATime()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_ADRenderer_JAVATimeHi_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVATimeHi()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_ADRenderer_JAVAVibrate_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.ADRenderer.JAVAVibrate(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

// ---- com.sandlotgames.snailmail.AccelerometerListener ----
jobject stub_AccelerometerListener_AccelerometerListener_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.AccelerometerListener.AccelerometerListener(LActivity;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_AccelerometerListener_start_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.AccelerometerListener.start()V called -- fill in from the real Java impl (jadx).");
}

void stub_AccelerometerListener_stop_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.AccelerometerListener.stop()V called -- fill in from the real Java impl (jadx).");
}

void stub_AccelerometerListener_onAccuracyChanged_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.AccelerometerListener.onAccuracyChanged(LSensor;I)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
}

void stub_AccelerometerListener_onSensorChanged_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.AccelerometerListener.onSensorChanged(LSensorEvent;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.sandlotgames.snailmail.MyOpenFeintDelegate ----
void stub_MyOpenFeintDelegate_userLoggedIn_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.MyOpenFeintDelegate.userLoggedIn(LCurrentUser;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.sandlotgames.snailmail.SnailMailActivity ----
jobject stub_SnailMailActivity_SnailMailActivity_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.SnailMailActivity()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SnailMailActivity_getContext_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.getContext()LContext; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_SnailMailActivity_wprintf_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.wprintf(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_SnailMailActivity_onCreate_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_SnailMailActivity_onDestroy_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onRestart_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onStart_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onStop_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onStop()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onPause_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onResume_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onResume()V called -- fill in from the real Java impl (jadx).");
}

void stub_SnailMailActivity_onWindowFocusChanged_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailActivity.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.sandlotgames.snailmail.SnailMailApplication ----
jobject stub_SnailMailApplication_SnailMailApplication_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailApplication.SnailMailApplication()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_SnailMailApplication_getContext_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailApplication.getContext()LContext; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_SnailMailApplication_onCreate_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.sandlotgames.snailmail.SnailMailApplication.onCreate()V called -- fill in from the real Java impl (jadx).");
}

